### ISSUE TITLE
Homebridge-comelit-vedo and RADAR exposition on HOME Assistant

### ISSUE THREAD

**Issue by iw6ovz** [madchicken/homebridge-comelit-vedo#7]
Hi,
I integrated the Comelit Vedo Homebridge feautures in Home Assistant throught the Controllor Homekit.
It's all right but Home Assistant shows only 2 RADAR elements but in Homebridge there are 12 RADAR elements (the same of the Comelit electrical system).
How can I show all the RADARS on Home Assistant? I installed plugin for comelit hub too and it works fine on Home Assistant.
Thanks,
Marco

**Comment by Marcoletto** [comment]
Hi,
I don't understand, Homebridge and Home Assistant are two different home automation open source; they do the same function.

So, why do you used both?

BTW, I want to use the comelit vedo IP in Home Assistant but I don't know how.

Can you help me?

Thanks, 
Marco

**Comment by madchicken** [comment]
Who is using both? I only use Homebridge and this is a plugin for Homebridge. I don't know anything about Home assistance, so I cannot help

**Comment by Marcoletto** [comment]
> Who is using both? I only use Homebridge and this is a plugin for Homebridge. I don't know anything about Home assistance, so I cannot help

Iw6ovz
